"use client";

import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import ProgressBar from "next-nprogress-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         {/* ProgressBar component from https://github.com/Skyleen77/next-nprogress-bar */}
        <ProgressBar
          height="4px"
          color="#fffd00"
          options={{ showSpinner: false }}
          shallowRouting
          appDirectory
        />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
